CREATE PROCEDURE PRAREAINSERT  
(		
	 @LINEID			INT
	,@AREACODE			VARCHAR(50)
	,@AREANAME			VARCHAR(50)
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @AREAID INT

	SELECT @AREAID = MAX(FLDAREAID)
	FROM TBLAREA

	INSERT INTO TBLAREA
	(
		 FLDAREAID
		,FLDLINEID
		,FLDAREACODE
		,FLDAREANAME
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@AREAID,0) + 1
		,@LINEID
		,@AREACODE
		,@AREANAME
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END