CREATE PROCEDURE PRAREAUPDATE
(	
	 @AREAID			INT
	,@LINEID			INT
	,@AREACODE			VARCHAR(50)
	,@AREANAME			VARCHAR(50)
	,@USERCODE			INT
)
AS
BEGIN
	UPDATE TBLAREA
	SET 
		 FLDLINEID			= @LINEID
		,FLDAREACODE		= @AREACODE
		,FLDAREANAME		= @AREANAME
		,FLDMODIFIEDDATE	= GETUTCDATE()
		,FLDMODIFIEDBY		= @USERCODE
	WHERE FLDAREAID			= @AREAID
END