CREATE PROCEDURE PRAREALIST
(	
	@AREAID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 FLDAREAID
		,FLDLINEID
		,FLDAREACODE
		,FLDAREANAME
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	FROM TBLAREA
	WHERE (@AREAID IS NULL OR FLDAREAID = @AREAID)
END