CREATE PROCEDURE PRCOMPANYINSERT  
(		
	 @COMPANYNAME	VARCHAR(250)
	,@SHORTCODE		VARCHAR(20)
	,@ADDRESS		NVARCHAR(500)
	,@CITY			VARCHAR(50)
	,@STATE			VARCHAR(50)
	,@COUNTRY		VARCHAR(50)
	,@USERCODE		INT
)
AS
BEGIN
	DECLARE @COMPANYID INT

	SELECT @COMPANYID = MAX(FLDCOMPANYID)
	FROM TBLCOMPANY

	INSERT INTO TBLCOMPANY
	(
		  FLDCOMPANYID
		 ,FLDCOMPANYNAME
		 ,FLDSHORTCODE
		 ,FLDADDRESS
		 ,FLDCITY
		 ,FLDSTATE
		 ,FLDCOUNTRY
		 ,FLDCREATEDDATE
		 ,FLDCREATEBY
		 ,FLDMODIFIEDDATE
		 ,FLDMODIFIEDBY
	)
	SELECT ISNULL(@COMPANYID,0) + 1
		,@COMPANYNAME
		,@SHORTCODE
		,@ADDRESS
		,@CITY
		,@STATE
		,@COUNTRY
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END