CREATE PROCEDURE PRCUSTOMERUPDATE
(	
	  @CUSTOMERID				INT			
	 ,@CUSTOMERCODE				VARCHAR(50)	
	 ,@FIRSTNAME				VARCHAR(50)	
	 ,@LASTNAME					VARCHAR(50)	
	 ,@DATEOFBIRTH				DATETIME	
	 ,@GOVTIDTYPEID				INT			
	 ,@GOVTIDTYPE				VARCHAR(50)	
	 ,@IDNUMBER					VARCHAR(50)	
	 ,@IDATTACHMENTPATH			VARCHAR(300)
	 ,@PROFPICPATH				VARCHAR(500)
	 ,@QRCODE					NVARCHAR(500)
	 ,@PHONENUMBER				VARCHAR(50)	
	 ,@AREAID					INT			
	 ,@LOCATION					VARCHAR(50)	
	 ,@ADDRESS				VARCHAR(50)	
	 ,@USERCODE					INT
)
AS
BEGIN
	UPDATE TBLCUSTOMER
	SET 
				
		 FLDCUSTOMERCODE		 = @CUSTOMERCODE		
		,FLDFIRSTNAME			 = @FIRSTNAME		
		,FLDLASTNAME			 = @LASTNAME			
		,FLDDATEOFBIRTH			 = @DATEOFBIRTH		
		,FLDGOVTIDTYPEID		 = @GOVTIDTYPEID		
		,FLDGOVTIDTYPE			 = @GOVTIDTYPE		
		,FLDIDNUMBER			 = @IDNUMBER			
		,FLDIDATTACHMENTPATH	 = @IDATTACHMENTPATH	
		,FLDPROFPICPATH			 = @PROFPICPATH		
		,FLDQRCODE				 = @QRCODE			
		,FLDPHONENUMBER			 = @PHONENUMBER		
		,FLDAREAID				 = @AREAID			
		,FLDLOCATION			 = @LOCATION			
		,FLDADDRESS				 = @ADDRESS			
		,FLDMODIFIEDDATE		 = GETUTCDATE()
		,FLDMODIFIEDBY			 = @USERCODE
	WHERE FLDCUSTOMERID			 = @CUSTOMERID
END