CREATE PROCEDURE PRCUSTOMERINSERT  
(		
	  @CUSTOMERCODE				VARCHAR(50)	
	 ,@FIRSTNAME				VARCHAR(50)	
	 ,@LASTNAME					VARCHAR(50)	
	 ,@DATEOFBIRTH				DATETIME	
	 ,@GOVTIDTYPEID				INT			
	 ,@GOVTIDTYPE				VARCHAR(50)	
	 ,@IDNUMBER					VARCHAR(50)	
	 ,@IDATTACHMENTPATH			VARCHAR(300)
	 ,@PROFPICPATH				VARCHAR(500)
	 ,@QRCODE					NVARCHAR(500)
	 ,@PHONENUMBER				VARCHAR(50)	
	 ,@AREAID					INT			
	 ,@LOCATION					VARCHAR(50)	
	 ,@ADDRESS				VARCHAR(50)	
	 ,@USERCODE					INT
)
AS
BEGIN
	
	DECLARE @CUSTOMERID INT

	SELECT @CUSTOMERID = MAX(FLDCUSTOMERID)
	FROM TBLCUSTOMER


	INSERT INTO TBLCUSTOMER
	(
		 FLDCUSTOMERID
		,FLDCUSTOMERCODE
		,FLDFIRSTNAME
		,FLDLASTNAME
		,FLDDATEOFBIRTH
		,FLDGOVTIDTYPEID
		,FLDGOVTIDTYPE
		,FLDIDNUMBER
		,FLDIDATTACHMENTPATH
		,FLDPROFPICPATH
		,FLDQRCODE
		,FLDPHONENUMBER
		,FLDAREAID
		,FLDLOCATION
		,FLDADDRESS
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@CUSTOMERID,0) + 1
		,@CUSTOMERCODE		
		,@FIRSTNAME		
		,@LASTNAME			
		,@DATEOFBIRTH		
		,@GOVTIDTYPEID		
		,@GOVTIDTYPE		
		,@IDNUMBER			
		,@IDATTACHMENTPATH	
		,@PROFPICPATH		
		,@QRCODE			
		,@PHONENUMBER		
		,@AREAID			
		,@LOCATION			
		,@ADDRESS			
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE

END