CREATE PROCEDURE PRINVESTORCAPITALINSERT  
(		
	 @INVESUSERCODE			 INT
	,@AMOUND				 DECIMAL(18,2)		
	,@DATE					 DATETIME
	,@TRANSACTIONTYPEID		 INT
	,@TRANSACTIONTYPE		 VARCHAR(5)
	,@COMPANYID				 INT
	,@USERCODE				 INT
)
AS
BEGIN
	DECLARE @INVESTORCAPITALID INT

	SELECT @INVESTORCAPITALID = MAX(FLDINVESTORCAPITALID)
	FROM TBLINVESTORCAPITAL

	INSERT INTO TBLINVESTORCAPITAL
	(
		 FLDINVESTORCAPITALID
		,FLDUSERCODE
		,FLDAMOUND
		,FLDDATE
		,FLDTRANSACTIONTYPEID
		,FLDTRANSACTIONTYPE
		,FLDCOMPANYID
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@INVESTORCAPITALID,0) + 1
		,@INVESUSERCODE		
		,@AMOUND			
		,@DATE				
		,@TRANSACTIONTYPEID	
		,@TRANSACTIONTYPE	
		,@COMPANYID			
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END