CREATE PROCEDURE PRLINELIST
(	
	@LINEID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		 
		 FLDLINECODE
		,FLDLINENAME
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	FROM TBLLINE
	WHERE (@LINEID IS NULL OR FLDLINEID =@LINEID)
END