CREATE PROCEDURE PRLOANLIST
(	
	@LOANID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		FLDLOANID
		,FLDLOANCODE
		,FLDCUSTOMERID
		,FLDSTATUS
		,FLDDISBURSEMENTDATE
		,FLDAMOUNT
		,FLDCOMPANYID
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	FROM TBLLOAN
	WHERE (@LOANID IS NULL OR FLDLOANID = @LOANID)
END