CREATE PROCEDURE PRLOANTYPELIST
(	
	@LOANTYPEID	INT	=	NULL
)
AS
BEGIN
	SELECT 
		FLDLOANTYPEID
		,FLDTYPECODE
		,FLDLOANNAME
		,FLDLOANID
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	FROM TBLLOANTYPE
	WHERE (@LOANTYPEID IS NULL OR FLDLOANTYPEID = @LOANTYPEID)
END