CREATE PROCEDURE PRLOANINSERT  

(		
	 @LOANCODE			VARCHAR(50)		
	,@CUSTOMERID		INT				
	,@STATUS			VARCHAR(50)		
	,@DISBURSEMENTDATE	DATETIME		
	,@AMOUNT			DECIMAL(18,2)	
	,@COMPANYID			INT				
	,@USERCODE			INT
)
AS
BEGIN
	DECLARE @LOANID INT

	SELECT @LOANID = MAX(FLDLOANID)
	FROM TBLLOAN

	INSERT INTO TBLLOAN
	(
		FLDLOANID
		,FLDLOANCODE
		,FLDCUSTOMERID
		,FLDSTATUS
		,FLDDISBURSEMENTDATE
		,FLDAMOUNT
		,FLDCOMPANYID
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@LOANID,0) + 1
		,@LOANCODE			
		,@CUSTOMERID		
		,@STATUS			
		,@DISBURSEMENTDATE	
		,@AMOUNT			
		,@COMPANYID			
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END