CREATE PROCEDURE PRLOANTYPEUPDATE
(	
	@LOANTYPEID		INT
	,@TYPECODE		VARCHAR(50)
	,@LOANNAME		VARCHAR(50)
	,@LOANID		INT
	,@USERCODE		INT
)
AS
BEGIN
	UPDATE TBLLOANTYPE
	SET 
		 FLDTYPECODE		 = @TYPECODE
		,FLDLOANNAME		 = @LOANNAME
		,FLDLOANID			 = @LOANID
		,FLDMODIFIEDDATE	 = GETUTCDATE()
		,FLDMODIFIEDBY		 = @USERCODE
	WHERE FLDLOANTYPEID		 = @LOANTYPEID
END