CREATE PROCEDURE PRLOANTYPEINSERT  

(		
	 @TYPECODE		VARCHAR(50)
	,@LOANNAME		VARCHAR(50)
	,@LOANID		INT
	,@USERCODE		INT
)
AS
BEGIN
	DECLARE @LOANTYPEID INT

	SELECT @LOANTYPEID = MAX(FLDLOANTYPEID)
	FROM TBLLOANTYPE

	INSERT INTO TBLLOANTYPE
	(
		 FLDLOANTYPEID
		,FLDTYPECODE
		,FLDLOANNAME
		,FLDLOANID
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT ISNULL(@LOANTYPEID,0) + 1
		,@TYPECODE
		,@LOANNAME
		,@LOANID
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE
END