CREATE PROCEDURE PRUSERUPDATE
(	
	 @USERCODEID				INT
	 ,@FIRSTNAME				VARCHAR(50)		
	 ,@LASTNAME					VARCHAR(50)		
	 ,@USERNAME					VARCHAR(50)		
	 ,@PASSWORD					NVARCHAR(50)	
	 ,@USERTYPEID				INT				
	 ,@USERTYPE					VARCHAR(50)		
	 ,@APPLICABLECOMPANYID		INT				
	 ,@APPLICABLECOMPANY		VARCHAR(50)		
	 ,@PHONENUMBER				VARCHAR(50)		
	 ,@DEFAULTCOMPANYID			INT				
	 ,@APPLICABLEAREA			VARCHAR(50)		
	 ,@PROFILEPICPATH			NVARCHAR(500)	
	 ,@USERCODE					INT
)
AS
BEGIN
	UPDATE TBLUSER
	SET 
		 FLDFIRSTNAME			 = @FIRSTNAME			
		,FLDLASTNAME			 = @LASTNAME				
		,FLDUSERNAME			 = @USERNAME				
		,FLDPASSWORD			 = HASHBYTES('MD5', N''+@PASSWORD+'')
		,FLDUSERTYPEID			 = @USERTYPEID			
		,FLDUSERTYPE			 = @USERTYPE				
		,FLDAPPLICABLECOMPANYID	 = @APPLICABLECOMPANYID	
		,FLDAPPLICABLECOMPANY	 = @APPLICABLECOMPANY	
		,FLDPHONENUMBER			 = @PHONENUMBER			
		,FLDDEFAULTCOMPANYID	 = @DEFAULTCOMPANYID		
		,FLDAPPLICABLEAREA		 = @APPLICABLEAREA		
		,FLDPROFILEPICPATH		 = @PROFILEPICPATH	
		,FLDMODIFIEDDATE		 = GETUTCDATE()
		,FLDMODIFIEDBY			 = @USERCODE
	WHERE FLDUSERCODE			 = @USERCODE
END
