CREATE PROCEDURE PRUSERINSERT  
(		
	  @FIRSTNAME				VARCHAR(50)		
	 ,@LASTNAME					VARCHAR(50)		
	 ,@USERNAME					VARCHAR(50)		
	 ,@PASSWORD					VARBINARY(50)	
	 ,@USERTYPEID				INT				
	 ,@USERTYPE					VARCHAR(50)		
	 ,@APPLICABLECOMPANYID		INT				
	 ,@APPLICABLECOMPANY		VARCHAR(50)		
	 ,@PHONENUMBER				VARCHAR(50)		
	 ,@DEFAULTCOMPANYID			INT				
	 ,@APPLICABLEAREA			VARCHAR(50)		
	 ,@PROFILEPICPATH			NVARCHAR(500)	
	 ,@USERCODE					INT
)
AS
BEGIN
	
	INSERT INTO TBLUSER
	(
		 FLDFIRSTNAME			
		,FLDLASTNAME				
		,FLDUSERNAME				
		,FLDPASSWORD				
		,FLDUSERTYPEID			
		,FLDUSERTYPE				
		,FLDAPPLICABLECOMPANYID	
		,FLDAPPLICABLECOMPANY	
		,FLDPHONENUMBER			
		,FLDDEFAULTCOMPANYID		
		,FLDAPPLICABLEAREA		
		,FLDPROFILEPICPATH		
		,FLDCREATEDDATE
		,FLDCREATEBY
		,FLDMODIFIEDDATE
		,FLDMODIFIEDBY
	)
	SELECT 
		 @FIRSTNAME			
		,@LASTNAME				
		,@USERNAME				
		,@PASSWORD				
		,@USERTYPEID			
		,@USERTYPE				
		,@APPLICABLECOMPANYID	
		,@APPLICABLECOMPANY	
		,@PHONENUMBER			
		,@DEFAULTCOMPANYID		
		,@APPLICABLEAREA		
		,@PROFILEPICPATH		
		,GETUTCDATE()
		,@USERCODE
		,GETUTCDATE()
		,@USERCODE

END