CREATE TABLE TBLAUDITAREA
(
	 FLDAUDITTYPE				INT						NOT NULL
	,FLDAUDITUSERCODE			INT						NOT NULL
	,FLDAUDITDATETIME			DATETIME				NOT NULL
	,FLDAUDITPROCEDURE			VARCHAR(128)			NOT NULL
	,FLDAREAID					INT						NOT NULL 
	,FLDLINEID					INT						NOT	NULL
	,FLDAREACODE				VARCHAR(50)					NULL 
	,FLDAREANAME				VARCHAR(50)					NULL
	,FLDCREATEDDATE				DATETIME				NOT NULL
	,FLDCREATEBY				INT						NOT	NULL
	,FLDMODIFIEDDATE			DATETIME				NOT NULL
	,FLDMODIFIEDBY				INT						NOT	NULL
	


)



