CREATE TABLE TBLAUDITLINE
(
	 FLDAUDITTYPE				INT						NOT NULL
	,FLDAUDITUSERCODE			INT						NOT NULL
	,FLDAUDITDATETIME			DATETIME				NOT NULL
	,FLDAUDITPROCEDURE			VARCHAR(128)			NOT NULL
	,FLDLINEID					INT						NOT NULL
	,FLDLINECODE				NVARCHAR(25)				NULL
	,FLDLINENAME				VARCHAR(50)					NULL
	,FLDCREATEDDATE				DATETIME				NOT NULL
	,FLDCREATEBY				INT						NOT	NULL
	,FLDMODIFIEDDATE			DATETIME				NOT NULL
	,FLDMODIFIEDBY				INT						NOT	NULL
	,FLDDTKEY					UNIQUEIDENTIFIER		NOT NULL


)

