CREATE TABLE TBLAUDITUSER
(
	 FLDAUDITTYPE				INT						NOT NULL
	,FLDAUDITUSERCODE			INT						NOT NULL
	,FLDAUDITDATETIME			DATETIME				NOT NULL
	,FLDAUDITPROCEDURE			VARCHAR(128)			NOT NULL
	,FLDUSERCODE				INT						NOT NULL
	,FLDFIRSTNAME				VARCHAR(50)					NULL
	,FLDLASTNAME				VARCHAR(50)					NULL
	,FLDUSERNAME				VARCHAR(50)					NULL
	,FLDPASSWORD				VARBINARY(50)			NOT NULL
	,FLDUSERTYPEID				INT							NULL
	,FLDUSERTYPE				VARCHAR(50)					NULL
	,FLDAPPLICABLECOMPANYID		INT							NULL
	,FLDAPPLICABLECOMPANY		VARCHAR(50)					NULL
	,FLDPHONENUMBER				VARCHAR(50)					NULL
	,FLDDEFAULTCOMPANYID		INT							NULL
	,FLDAPPLICABLEAREA			VARCHAR(50)					NULL
	,FLDPROFILEPICPATH			NVARCHAR(500)				NULL
	,FLDCREATEDDATE				DATETIME				NOT NULL
	,FLDCREATEBY				INT						NOT	NULL
	,FLDMODIFIEDDATE			DATETIME				NOT NULL
	,FLDMODIFIEDBY				INT						NOT	NULL


)



