CREATE TABLE TBLCUSTOMER
(
	 FLDCUSTOMERID				INT				    NOT NULL  
	,FLDCUSTOMERCODE			VARCHAR(50)				NULL
	,FLDFIRSTNAME				VARCHAR(50)				NULL
	,FLDLASTNAME				VARCHAR(50)				NULL
	,FLDDATEOFBIRTH				DATETIME				NULL
	,FLDGOVTIDTYPEID			INT						NULL
	,FLDGOVTIDTYPE				VARCHAR(50)				NULL
	,FLDIDNUMBER				VARCHAR(50)				NULL
	,FLDIDATTACHMENTPATH		VARCHAR(300)			NULL
	,FLDPROFPICPATH				VARCHAR(500)			NULL
	,FLDQRCODE					NVARCHAR(500)			NULL
	,FLDPHONENUMBER				VARCHAR(50)				NULL
	,FLDAREAID					INT						NULL
	,FLDLOCATION				VARCHAR(50)				NULL
	,FLDADDRESS					VARCHAR(50)				NULL
	,FLDCREATEDDATE				DATETIME			NOT NULL
	,FLDCREATEBY				INT					NOT	NULL
	,FLDMODIFIEDDATE			DATETIME			NOT NULL
	,FLDMODIFIEDBY				INT					NOT	NULL
	CONSTRAINT PK_TBLCUSTOMER PRIMARY KEY
	(
		FLDCUSTOMERID ASC
	)

)

