CREATE TABLE TBLCOMPANY
(
	 FLDCOMPANYID			INT				    NOT NULL 
	,FLDCOMPANYNAME			VARCHAR(250)	    NOT NULL
	,FLDSHORTCODE			VARCHAR(20)		    NOT NULL 
	,FLDADDRESS				NVARCHAR(500)			NULL
	,FLDCITY				VARCHAR(50)				NULL
	,FLDSTATE				VARCHAR(50)				NULL
	,FLDCOUNTRY				VARCHAR(50)				NULL
	,FLDCREATEDDATE			DATETIME			NOT NULL
	,FLDCREATEBY			INT					NOT	NULL
	,FLDMODIFIEDDATE		DATETIME			NOT NULL
	,FLDMODIFIEDBY			INT					NOT	NULL
	CONSTRAINT PK_TBLCOMPANY PRIMARY KEY
	(
		FLDCOMPANYID ASC
	)

)

