CREATE TABLE TBLINVESTORCAPITAL
(
	 FLDINVESTORCAPITALID			INT				    NOT NULL  
	,FLDUSERCODE					INT						NULL
	,FLDAMOUND						DECIMAL(18,2)			NULL
	,FLDDATE						DATETIME				NULL
	,FLDTRANSACTIONTYPEID			INT						NULL
	,FLDTRANSACTIONTYPE				VARCHAR(1)				NULL
	,FLDCOMPANYID					INT						NULL
	,FLDCREATEDDATE					DATETIME			NOT NULL
	,FLDCREATEBY					INT					NOT	NULL
	,FLDMODIFIEDDATE				DATETIME			NOT NULL
	,FLDMODIFIEDBY					INT					NOT	NULL
	CONSTRAINT PK_TBLINVESTORCAPITAL PRIMARY KEY
	(
		FLDINVESTORCAPITALID ASC
	)

)

