CREATE TABLE TBLLOAN
(
	 FLDLOANID						INT				    NOT NULL  
	,FLDLOANCODE					VARCHAR(50)				NULL
	,FLDCUSTOMERID					INT						NULL
	,FLDSTATUS						VARCHAR(50)				NULL
	,FLDDISBURSEMENTDATE			DATETIME				NULL
	,FLDAMOUNT						DECIMAL(18,2)			NULL
	,FLDCOMPANYID					INT						NULL
	,FLDCREATEDDATE					DATETIME			NOT NULL
	,FLDCREATEBY					INT					NOT	NULL
	,FLDMODIFIEDDATE				DATETIME			NOT NULL
	,FLDMODIFIEDBY					INT					NOT	NULL
	CONSTRAINT PK_TBLLOAN PRIMARY KEY
	(
		FLDLOANID ASC
	)

)

