CREATE TABLE TBLLOANTYPE
(
	 FLDLOANTYPEID					INT				    NOT NULL  
	,FLDTYPECODE					VARCHAR(50)				NULL
	,FLDLOANNAME					VARCHAR(50)				NULL
	,FLDLOANID						INT						NULL
	,FLDCREATEDDATE					DATETIME			NOT NULL
	,FLDCREATEBY					INT					NOT	NULL
	,FLDMODIFIEDDATE				DATETIME			NOT NULL
	,FLDMODIFIEDBY					INT					NOT	NULL
	CONSTRAINT PK_TBLLOANTYPE PRIMARY KEY
	(
		FLDLOANTYPEID ASC
	)

)

