CREATE TABLE TBLUSER
(
	 FLDUSERCODE				INT				    NOT NULL  IDENTITY(1,1)
	,FLDFIRSTNAME				VARCHAR(50)				NULL
	,FLDLASTNAME				VARCHAR(50)				NULL 
	,FLDUSERNAME				VARCHAR(50)				NULL
	,FLDPASSWORD				VARBINARY(50)		NOT NULL			
	,FLDUSERTYPEID				INT						NULL
	,FLDUSERTYPE				VARCHAR(50)				NULL
	,FLDAPPLICABLECOMPANYID		INT						NULL
	,FLDAPPLICABLECOMPANY		VARCHAR(50)				NULL	
	,FLDPHONENUMBER				VARCHAR(50)				NULL
	,FLDDEFAULTCOMPANYID		INT						NULL
	,FLDAPPLICABLEAREA			VARCHAR(50)				NULL
	,FLDPROFILEPICPATH			NVARCHAR(500)			NULL
	,FLDCREATEDDATE				DATETIME			NOT NULL
	,FLDCREATEBY				INT					NOT	NULL
	,FLDMODIFIEDDATE			DATETIME			NOT NULL
	,FLDMODIFIEDBY				INT					NOT	NULL
	CONSTRAINT PK_TBLUSER PRIMARY KEY
	(
		FLDUSERCODE ASC
	)

)

